# Generated by Django 5.0.6 on 2024-11-25 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BS', 'Bousanm')], max_length=10, unique=True)),
                ('value', models.IntegerField(default=24000)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('date_naissance', models.CharField(max_length=255)),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('pass_send', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='customers_imgs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('etat', models.CharField(choices=[('temporaire', 'Temporaire'), ('final', 'Final')], default='temporaire', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9, unique=True)),
                ('type_compte', models.CharField(choices=[('SOL', 'Sol'), ('BS', 'Bousanm')], max_length=255)),
                ('solde_PL', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solde_M', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solde_S', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solde_BS', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('devise', models.CharField(choices=[('HTG', 'HTG'), ('USD', 'USD')], default='HTG', max_length=10)),
                ('etat', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=20)),
                ('Online_Created', models.BooleanField(default=False)),
                ('dureeP', models.CharField(default='N/A', max_length=10)),
                ('dureeM', models.CharField(choices=[('6', '6 Mois'), ('9', '9 Mois'), ('12', '12 Mois'), ('N/A', 'N/A')], default='N/A', max_length=10)),
                ('interet', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_debutP', models.DateField(blank=True, null=True)),
                ('date_debutM', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('nb_main', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sol', models.IntegerField()),
                ('montant_jours', models.IntegerField(editable=False)),
                ('next_run_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
