# Generated by Django 5.0.6 on 2024-11-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_compte_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='montant_jours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='nb_main',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='sol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
